### ISSUE TITLE
Unable to generate travis template

### ISSUE THREAD

**Issue by ChristianWitts** [antifuchs/cargo-template-ci#1]
Steps to reproduce.

1. Fresh project, `cargo init --bin me && cd me`
2. `cargo +nightly install cargo-template-ci`
3. `RUST_BACKTRACE=1 cargo +nightly template-ci`

Expected to have a `.travisci.yml` file generated, actual results

```
➜  git:(master) RUST_BACKTRACE=1 cargo template-ci
thread 'main' panicked at 'Could not parse config: Error("invalid type: null, expected struct Metadata", line: 1, column: 4)', libcore/result.rs:1009:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::_print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::continue_panic_fmt
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::result::unwrap_failed
   9: cargo_template_ci::main
  10: std::rt::lang_start::{{closure}}
  11: std::panicking::try::do_call
  12: __rust_maybe_catch_panic
  13: std::rt::lang_start_internal
  14: main
```

**Comment by antifuchs** [comment]
...huh. Can you paste me your `Cargo.toml` file? I think I understand what it is (guess that if there's no `package.metadata`, the config file parser is unhappy), but would like to validate / write a test for it so it stays fixed (:

**Comment by antifuchs** [comment]
Oh wait no, I can totally repro this with the steps you provided, sorry. I'll try and fix this (:

**Comment by ChristianWitts** [comment]
Thanks very much @antifuchs :)
